### ISSUE TITLE
BBCode does not apply when translating in some languages.

### ISSUE THREAD

**Issue by cacapon** [GDQuest/GDTour#39]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When translating in languages that use non-alphabetic languages, the BBCode modifiers may not work.
(at least not reflected in Japanese)

The following pictures compare the original with the Japanese translation.
The four elements in the middle section are not emphasized. (Scenes, Nodes, Scripts and Signals)
Also not emphasized is "Let's go started!"

![image](https://github.com/GDQuest/godot-tours/assets/47442969/55291719-e309-4eac-9814-89e219cbfeef)

**What is the expected behavior?**
I believe that words emphasized in English should be able to be emphasized in other languages.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Follow [this documents](https://github.com/GDQuest/godot-tours/blob/main/documentation/translating_godot_tours.md) to create a po file for Japanese.
3. Create a `locale` folder under `res://tours/godot-first-tour/`.
4. Put po file in locale.
5. Change to Japanese before the project starts.
6. Start Godot Tours.
7. Translated, but accent is invalid.

## Other ##

**Other information** 

- OS: MacOS 14.1.2
- Godot: 4.2.0
- Godot Tours: 0.3.1

---

**Reasons** 
As far as I have been able to find out, I believe that the reason is that the poppins font does not support Japanese.

I checked BBCode with RichTextLabel using the Poppins font.
I checked in Japanese, Chinese, and Korean and found the symptoms of no highlighting in Japanese and Chinese.

![image](https://github.com/GDQuest/godot-tours/assets/47442969/75c960af-69cb-4a9b-91a8-9d6feb9679f4)

I have a suggestion for a solution. I have confirmed that at least Japanese can be highlighted with the system font.
So we think that the problem can be avoided by setting the non-alphabetic languages to use the system font.
(We do not know if this solution will work smoothly as it is just an idea...)

**Comment by NathanLovato** [comment]
Using system fonts if the language is CJK or Cyrillic or another language unsupported by Poppins and Montserrat (I think both fonts are used currently) sounds like a great plan. It should definitely be possible!

**Comment by razcore-rad** [comment]
We talked about two solutions here:
1. Set up a series of `SystemFont` fallbacks depending on the OSes so it uses the default of the respective OSes.
2. Use fallback fonts and expand as needed based on added languages. So for example for Japanese we would use [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP?query=noto), for Korean it would be the Korean version and so on.

I worked on the scaffolding for 2. for the Japanese example, adding a [`theme_utils.gd::request_fallback_font()`](https://github.com/GDQuest/godot-tours/blob/ec3ea84f3dde983aa2bbd82ff41ca9739f6849ac/addons/godot_tours/ui/theme_utils.gd#L91) function and it's used in [`bubble.gd::_ready()`](https://github.com/GDQuest/godot-tours/blob/ec3ea84f3dde983aa2bbd82ff41ca9739f6849ac/addons/godot_tours/bubble/bubble.gd#L85).

*Note* that it should be used in `ui_welcome_menu.gd::_ready()` as well which isn't at the moment. I just implemented this prototype solution so we have something to discuss.

**Comment by cacapon** [comment]
I was working on the translation in GDQuest 0.4.1 and I am reporting that the highlighting was done.

Sorry, I could not determine whether it is in the process of being addressed or has been addressed.

![image](https://github.com/GDQuest/GDTour/assets/47442969/bd234e36-f313-4919-a9b3-0746fb277c1d)

**Comment by NathanLovato** [comment]
Razvan did some work to address this. If it's working for you too now, great! We can close the issue then. I forgot to close it.
